USE dock;

CREATE TABLE `pessoas` (
	`ID_PESSOA` INT NOT NULL AUTO_INCREMENT COMMENT 'ID da Pessoa',
	`NM_PESSOA` VARCHAR(50) NOT NULL COMMENT 'Nome Pessoa',
	`NU_CPF` VARCHAR(11) NOT NULL COMMENT 'Numero CPF',
	`DT_NASCIMENTO` DATE NOT NULL COMMENT 'Data Nascimento',
	PRIMARY KEY (`ID_PESSOA`)
) ;

ALTER TABLE `pessoas` 
ADD CONSTRAINT UNIQUE_PESSOAS_CPF
UNIQUE (NU_CPF);


CREATE TABLE `contas` (
	`ID_CONTA` INT NOT NULL AUTO_INCREMENT COMMENT 'ID da Conta',
	`ID_PESSOA` INT NOT NULL COMMENT 'ID Pessoa',
	`VL_SALDO` REAL NOT NULL DEFAULT '0' COMMENT 'Saldo',
	`VL_LIMITE_SAQUE_DIARIO` REAL NOT NULL DEFAULT '0' COMMENT 'Limite Saque Diario',
	`IC_TIPO_CONTA` INT NOT NULL COMMENT 'Tipo Conta',
	`IS_FLAG_ATIVO` BOOLEAN NOT NULL COMMENT 'Flag Ativo',
	`DT_CRIACAO` DATE NOT NULL COMMENT 'Data Criacao',
	PRIMARY KEY (`ID_CONTA`),
	FOREIGN KEY (ID_PESSOA) REFERENCES pessoas(ID_PESSOA)
);


ALTER TABLE `contas` 
ADD CONSTRAINT CHECK_CONTAS_TIPO_CONTA
CHECK (0 OR 1 OR 2);


CREATE TABLE `transacoes` (
	`ID_TRANSACAO` INT NOT NULL AUTO_INCREMENT COMMENT 'ID Transacao',
	`ID_CONTA` INT NOT NULL COMMENT 'ID Conta',
	`VL_VALOR` REAL NOT NULL COMMENT 'Valor',
	`IC_TIPO` INT NOT NULL COMMENT 'Tipo Transacao (0:deposito,1:saque)',
	`DT_TRANSACAO` DATE NOT NULL COMMENT 'Data Transacao',
	PRIMARY KEY (`ID_TRANSACAO`),
	FOREIGN KEY (ID_CONTA) REFERENCES contas(ID_CONTA)
) ;

ALTER TABLE `transacoes` 
ADD CONSTRAINT CHECK_TRANSACOES_TIPO
CHECK (0 OR 1);
